### PR TITLE
Mod Info Bundle Support

### PR DESCRIPTION
**Pull request by Jab005**
Makes mod info support the bundle

(Image here is an old screenshot, Indonesian version typo was already been fixed)
Screenshot_2024_0702_090927_io anuke mindustry
Screenshot_2024_0702_091013_io anuke mindustry

### CODE REVIEW

**Comment by Jab005** [comment]
I'll wait till reviewed.
May there's still unexpected typo i made in bundles...

**Comment by Jab005** [comment]
Anyway if you don't understand the js code, let it
I've tested it and it's worked

**Review by zuoranartemwing — APPROVED** [review]

**Comment by WilloIzCitron** [comment]
yes, this feature was inspired by [Testing Util](https://github.com/MEEPofFaith/testing-utilities-java)

**Review by WilloIzCitron — APPROVED** [review]

**Comment by Jab005** [comment]
> yes, this feature was inspired by [Testing Util](https://github.com/MEEPofFaith/testing-utilities-java)

But im inspired by sapphirium :v
Also learning more through source code

**Pull request merged**
